spring:
  application:
    name: springboottutorial
server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: pass123
welcome:
  message: Welcome to daily code buffer!!!